### PR TITLE
MNT #43 replace NXmonochromator with NXbeam

### LINKED ISSUE #43: entry/instrument requires polarization field
soft x-ray beamlines at ALS and NSLS-ii regularly change the polarization.

The value can be plain text like "vertical", "C+" "circular left".   How should we proceed with this?

### PR DESCRIPTION
**Pull request by prjemian**
Fix #43 by:

* replacing `monochromator`NXmonochromator (NXmonochromator) group with `incident_beam` (NXbeam) group
* relocating `monochromator/energy` into `incident_beam/incident_energy` (consistent with NeXus field name)
* creating `incident_beam/incident_polarization` (consistent with NeXus field name)

### CODE REVIEW

**Comment by prjemian** [comment]
This is ready for review.

**Review by JulReinhardt — APPROVED** [review]

**Review by AbbyGi — APPROVED** [review]

**Review by ambarb — APPROVED** [review]

**Review by ambarb — CHANGES_REQUESTED** [review]
I see we forgot to make some issues regarding slide 16 from the survey results (#57 )

- [ ] **energy resolution** (this is linked to expected longitudinal coherence) --> lets use `incident_energy_spread` like the standard "wavelength" in NX beam, but NXptycho has done this - so we will copy [NXptycho](https://manual.nexusformat.org/classes/contributed_definitions/NXcxi_ptycho.html#nxcxi-ptycho-entry-1-instrument-1-beam-1-incident-energy-spread-field)
- [ ] **probe size - vertical and horizontal** (linked to transverse coherence and minimum speckle size) USE [extent[2, j]](https://manual.nexusformat.org/classes/base_classes/NXbeam.html#nxbeam-extent-field) like NXptycho lead by @JulReinhardt [NXptycho ](https://github.com/lightsources/NX-cxi-ptycho/blob/nexus-definition/NeXus/NXptycho.nxdl.xml)
- [x] **aperture-sample distance** (this is linked to the kind of probe citing the sample) , and there should be an option for 'NA" or "focused probe" as some beamlines are using focusing objects ---> **we will skip this because this book-keeping for exp, pytcho isn't doing it, and really the probe size matters most.  Future change is possible but it is not clear what existing NXdefinition will work.** 
- [x] perhaps we add **optics-sample distance** (this would be if someone were using a kinoform or other kind of optic that the Beamline wants to keep track of because they VARY the distance depending on the experiment) --->redundant with  **aperture-sample distance**.  Any future change should try to capture both?

I think all of these items I just listed can be optional as some user groups may not care at all, but some do care very much.

@prjemian , happy to make a new issue if you prefer.

**Comment by prjemian** [comment]
There is a [`NXsample/distance` field](https://manual.nexusformat.org/classes/base_classes/NXsample.html#nxsample-distance-field) but this is different from `optics-sample distance`.  Still, I believe this field belongs in the `NXsample` group (which be in a different issue).

**Comment by prjemian** [comment]
We made some changes in the check list (above) today.  I'll update this PR.

**Comment by prjemian** [comment]
@JulReinhardt , @ambarb , @AbbyGi : We **must** change `incident_polarization` to a different name since NeXus NXbeam uses [`incident_polarization`](https://manual.nexusformat.org/classes/base_classes/NXbeam.html#nxbeam-incident-polarization-field) to describe numerical values.  We say this term should be descriptive text.

`incident_polarization`  --> `incident_polarization_type`

Fortunately, this change will not affect any other code we have now:

``bash
(base) prjemian@zap:~/.../xpcs/NeXus$ git grep incident_polarization
NXxpcs.nxdl.xml:        <field name="incident_polarization">
```

**Comment by prjemian** [comment]
And, this file is out of sync with master branch.  Must first wait for PR #52.

**Comment by prjemian** [comment]
@ambarb ready for your review

**Review by ambarb — APPROVED** [review]

**Pull request merged**
